apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubescraper
  labels:
    app: youtubescraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtubescraper
  template:
    metadata:
      labels:
        app: youtubescraper
    spec:
      containers:
      - name: youtubescraper
        image: 615299753054.dkr.ecr.us-east-1.amazonaws.com/youtubescraper:latest
        env:
        - name: KAFKA_BROKER
          value: kafka-svc:9093  # Kafka 브로커 주소
        ports:
        - containerPort: 8080
